name: Deploy Backend Functions
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project dreampos-94155
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POSZAMBO }}